/**
 * 通话模块颜色定义
 * 对应Flutter call_colors.dart
 */
export class CallColors {
  static readonly colorWhite: string = '#FFFFFF';
  static readonly colorG7: string = '#D5E0F2';
  static readonly colorG5: string = '#8F9AB2';
  static readonly colorDarkBg: string = '#2D2D2D';
  static readonly colorControlsBg: string = '#343842';
  static readonly colorHangup: string = '#FF4444';
  static readonly colorAccept: string = '#2DCE89';
}
