export class RoomColors {
  static readonly g2: string = '#FF22262E';
  static readonly g3: string = '#FF4E5461';
  static readonly g4: string = '#FF6B758A';
  static readonly g5: string = '#FF8F9AB2';
  static readonly g6: string = '#FFC5CCDC';
  static readonly g7: string = '#FFE7ECF6';
  static readonly g8: string = '#FFF2F5FC';
  static readonly b1: string = '#FF1C66E5';
  static readonly b1d: string = '#FF4791FF';
  static readonly brandBlue: string = '#FF006EFF';
  static readonly background: string = '#FFF8F9FB';
  static readonly cardBackground: string = '#FFFFFFFF';
  static readonly white: string = '#FFFFFFFF';
  static readonly black: string = '#FF000000';
  static readonly translucentLightBlack: string = '#88121723';
  static readonly fluorescentGreen: string = '#FF1AFFC9';
  static readonly darkBlack: string = '#FF0F1014';
  static readonly lightGrey: string = '#FF2A2D38';
  static readonly exitRed: string = '#FFED414D';
  static readonly mainBlack: string = '#FF17181F';
  static readonly dividerGrey: string = '#4D4F586B';
  static readonly dividerGreyWith10Alpha: string = '#1A4F586B';
  static readonly dividerGreyWith20Alpha: string = '#334F586B';
  static readonly searchBarGrey: string = '#FF2A2D38';
  static readonly buttonGrey: string = '#FF4F5861';
  static readonly adminOrange: string = '#FFF06C4B';
}
