export class Constants {
  static readonly PREF_NAME: string = 'trtc_user_prefs';
  static readonly KEY_USER_ID: string = 'userId';
  static readonly KEY_NICKNAME: string = 'nickname';
  static readonly KEY_AVATAR_URL: string = 'avatarUrl';
  static readonly KEY_AUTO_LOGIN: string = 'autoLogin';
  static readonly DEFAULT_AVATAR_URL: string = 'https://im.sdk.qcloud.com/download/tuikit-resource/avatar/avatar_1.png';
}
